version: '3.8'

services:

  mysql:
    image: mysql:8
    container_name: mysql-db

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: employee_db
      MYSQL_USER: sai
      MYSQL_PASSWORD: sai

    ports:
      - "3306:3306"

    volumes:
      - mysql-data:/var/lib/mysql

  employee-app:
    build: ./backend

    container_name: employee-app

    depends_on:
      - mysql

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/employee_db
      SPRING_DATASOURCE_USERNAME: sai
      SPRING_DATASOURCE_PASSWORD: sai

    ports:
      - "8080:8080"

  frontend:
    build: ./frontend

    container_name: frontend

    depends_on:
      - employee-app

    ports:
      - "3000:80"

  nginx:
    image: nginx:latest

    container_name: nginx

    depends_on:
      - frontend
      - employee-app

    ports:
      - "80:80"

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

volumes:
  mysql-data:
