events {}

http {

    server {
        listen 80;

        location / {
            proxy_pass http://frontend:80;
        }

        location /employees {
            proxy_pass http://employee-app:8080;
        }
    }
}
