events {}

http {

    upstream backend {
        server employee-app:8080;
    }

    server {

        listen 80;

        location / {
            proxy_pass http://frontend;
        }

        location /api/ {
            proxy_pass http://backend/;
        }
    }

    upstream frontend {
        server frontend:80;
    }
}
